### ISSUE TITLE
Ghost recording doesn't work with rolls

### ISSUE THREAD

**Issue by mpwoz** [4D4XFUN/bevy-jam-5#46]
Rolls multiply velocity when applying it to position (without actually saving velocity in the movement controller).

Since ghosts record velocity, they break when the player rolls.

Alternative approaches:
- record position instead (would break animation)
- record timestamps and grid positions and navigate between them using variable acceleration (animation works, tricky to implement correctly)
- record timestamps and grid positions and lerp between them, create a new animation system for ghosts (or don't, they're floaty)

**Comment by tigerplush** [comment]
This is fixed with #49 , I just recorded the animation state 🤣
